// Generated by gencpp from file asv/arduino.msg
// DO NOT EDIT!


#ifndef ASV_MESSAGE_ARDUINO_H
#define ASV_MESSAGE_ARDUINO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asv
{
template <class ContainerAllocator>
struct arduino_
{
  typedef arduino_<ContainerAllocator> Type;

  arduino_()
    : battery_voltage(0.0)
    , prop_demand(0.0)
    , voltage_demand(0.0)  {
    }
  arduino_(const ContainerAllocator& _alloc)
    : battery_voltage(0.0)
    , prop_demand(0.0)
    , voltage_demand(0.0)  {
    }



   typedef float _battery_voltage_type;
  _battery_voltage_type battery_voltage;

   typedef float _prop_demand_type;
  _prop_demand_type prop_demand;

   typedef float _voltage_demand_type;
  _voltage_demand_type voltage_demand;




  typedef boost::shared_ptr< ::asv::arduino_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv::arduino_<ContainerAllocator> const> ConstPtr;

}; // struct arduino_

typedef ::asv::arduino_<std::allocator<void> > arduino;

typedef boost::shared_ptr< ::asv::arduino > arduinoPtr;
typedef boost::shared_ptr< ::asv::arduino const> arduinoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv::arduino_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv::arduino_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'asv': ['/home/ric_94/catkin_ws/src/asv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv::arduino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv::arduino_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv::arduino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv::arduino_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv::arduino_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv::arduino_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv::arduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c206d8bc0371a0b0ba4915d805666d5f";
  }

  static const char* value(const ::asv::arduino_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc206d8bc0371a0b0ULL;
  static const uint64_t static_value2 = 0xba4915d805666d5fULL;
};

template<class ContainerAllocator>
struct DataType< ::asv::arduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv/arduino";
  }

  static const char* value(const ::asv::arduino_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv::arduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 battery_voltage\n\
float32 prop_demand\n\
float32 voltage_demand\n\
";
  }

  static const char* value(const ::asv::arduino_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv::arduino_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.battery_voltage);
      stream.next(m.prop_demand);
      stream.next(m.voltage_demand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct arduino_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv::arduino_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv::arduino_<ContainerAllocator>& v)
  {
    s << indent << "battery_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.battery_voltage);
    s << indent << "prop_demand: ";
    Printer<float>::stream(s, indent + "  ", v.prop_demand);
    s << indent << "voltage_demand: ";
    Printer<float>::stream(s, indent + "  ", v.voltage_demand);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MESSAGE_ARDUINO_H
