// Generated by gencpp from file asv/headingd.msg
// DO NOT EDIT!


#ifndef ASV_MESSAGE_HEADINGD_H
#define ASV_MESSAGE_HEADINGD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asv
{
template <class ContainerAllocator>
struct headingd_
{
  typedef headingd_<ContainerAllocator> Type;

  headingd_()
    : heading_demand(0.0)  {
    }
  headingd_(const ContainerAllocator& _alloc)
    : heading_demand(0.0)  {
    }



   typedef float _heading_demand_type;
  _heading_demand_type heading_demand;




  typedef boost::shared_ptr< ::asv::headingd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv::headingd_<ContainerAllocator> const> ConstPtr;

}; // struct headingd_

typedef ::asv::headingd_<std::allocator<void> > headingd;

typedef boost::shared_ptr< ::asv::headingd > headingdPtr;
typedef boost::shared_ptr< ::asv::headingd const> headingdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv::headingd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv::headingd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'asv': ['/home/ric_94/catkin_ws/src/asv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv::headingd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv::headingd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv::headingd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv::headingd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv::headingd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv::headingd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv::headingd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a033fb24cad4dc624033484eb21eea63";
  }

  static const char* value(const ::asv::headingd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa033fb24cad4dc62ULL;
  static const uint64_t static_value2 = 0x4033484eb21eea63ULL;
};

template<class ContainerAllocator>
struct DataType< ::asv::headingd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv/headingd";
  }

  static const char* value(const ::asv::headingd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv::headingd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 heading_demand\n\
\n\
";
  }

  static const char* value(const ::asv::headingd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv::headingd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading_demand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct headingd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv::headingd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv::headingd_<ContainerAllocator>& v)
  {
    s << indent << "heading_demand: ";
    Printer<float>::stream(s, indent + "  ", v.heading_demand);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MESSAGE_HEADINGD_H
