// Generated by gencpp from file asv/position.msg
// DO NOT EDIT!


#ifndef ASV_MESSAGE_POSITION_H
#define ASV_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asv
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : X(0.0)
    , Y(0.0)
    , speed(0.0)
    , lat(0.0)
    , long(0.0)
    , time(0.0)
    , ValidGPSfix(0)
    , number_of_satellites(0)  {
    }
  position_(const ContainerAllocator& _alloc)
    : X(0.0)
    , Y(0.0)
    , speed(0.0)
    , lat(0.0)
    , long(0.0)
    , time(0.0)
    , ValidGPSfix(0)
    , number_of_satellites(0)  {
    }



   typedef float _X_type;
  _X_type X;

   typedef float _Y_type;
  _Y_type Y;

   typedef float _speed_type;
  _speed_type speed;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _long_type;
  _long_type long;

   typedef double _time_type;
  _time_type time;

   typedef int8_t _ValidGPSfix_type;
  _ValidGPSfix_type ValidGPSfix;

   typedef int8_t _number_of_satellites_type;
  _number_of_satellites_type number_of_satellites;




  typedef boost::shared_ptr< ::asv::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::asv::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::asv::position > positionPtr;
typedef boost::shared_ptr< ::asv::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'asv': ['/home/ric_94/catkin_ws/src/asv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ff27e09213a0df37db82ae00fb8aecd";
  }

  static const char* value(const ::asv::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ff27e09213a0df3ULL;
  static const uint64_t static_value2 = 0x7db82ae00fb8aecdULL;
};

template<class ContainerAllocator>
struct DataType< ::asv::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv/position";
  }

  static const char* value(const ::asv::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 X\n\
float32 Y\n\
float32 speed\n\
float64 lat\n\
float64 long\n\
float64 time\n\
int8 ValidGPSfix\n\
int8 number_of_satellites\n\
";
  }

  static const char* value(const ::asv::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.speed);
      stream.next(m.lat);
      stream.next(m.long);
      stream.next(m.time);
      stream.next(m.ValidGPSfix);
      stream.next(m.number_of_satellites);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv::position_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "long: ";
    Printer<double>::stream(s, indent + "  ", v.long);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "ValidGPSfix: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ValidGPSfix);
    s << indent << "number_of_satellites: ";
    Printer<int8_t>::stream(s, indent + "  ", v.number_of_satellites);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MESSAGE_POSITION_H
