// Generated by gencpp from file asv/status.msg
// DO NOT EDIT!


#ifndef ASV_MESSAGE_STATUS_H
#define ASV_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asv
{
template <class ContainerAllocator>
struct status_
{
  typedef status_<ContainerAllocator> Type;

  status_()
    : nodeID(0)
    , status(false)  {
    }
  status_(const ContainerAllocator& _alloc)
    : nodeID(0)
    , status(false)  {
    }



   typedef int32_t _nodeID_type;
  _nodeID_type nodeID;

   typedef uint8_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::asv::status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv::status_<ContainerAllocator> const> ConstPtr;

}; // struct status_

typedef ::asv::status_<std::allocator<void> > status;

typedef boost::shared_ptr< ::asv::status > statusPtr;
typedef boost::shared_ptr< ::asv::status const> statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv::status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv::status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'asv': ['/home/ric_94/catkin_ws/src/asv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv::status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv::status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv::status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv::status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv::status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "722a3850d404093d2b94283695c2a465";
  }

  static const char* value(const ::asv::status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x722a3850d404093dULL;
  static const uint64_t static_value2 = 0x2b94283695c2a465ULL;
};

template<class ContainerAllocator>
struct DataType< ::asv::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv/status";
  }

  static const char* value(const ::asv::status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nodeID\n\
bool status\n\
";
  }

  static const char* value(const ::asv::status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv::status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeID);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv::status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv::status_<ContainerAllocator>& v)
  {
    s << indent << "nodeID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nodeID);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MESSAGE_STATUS_H
